package requests

type Header struct {
	ExchangedOrdersDocumentIdentifier                        string   `json:"ExchangedOrdersDocumentIdentifier"`
	OrdersDocument                                           *string  `json:"OrdersDocument"`
	ExchangedDocumentContextSpecifiedTransactionIdentifier   *string  `json:"ExchangedDocumentContextSpecifiedTransactionIdentifier"`
	ExchangedOrdersDocumentName                              *string  `json:"ExchangedOrdersDocumentName"`
	ExchangedOrdersDocumentTypeCode                          *string  `json:"ExchangedOrdersDocumentTypeCode"`
	ExchangedOrdersDocumentIssueDate                         *string  `json:"ExchangedOrdersDocumentIssueDate"`
	ExchangedOrdersDocumentPurposeCode                       *string  `json:"ExchangedOrdersDocumentPurposeCode"`
	ExchangedOrdersDocumentRevisionDate                      *string  `json:"ExchangedOrdersDocumentRevisionDate"`
	ExchangedOrdersDocumentRevisionIdentifier                *string  `json:"ExchangedOrdersDocumentRevisionIdentifier"`
	ExchangedOrdersDocumentStatusCode                        *string  `json:"ExchangedOrdersDocumentStatusCode"`
	ExchangedOrdersDocumentSubtypeCode                       *string  `json:"ExchangedOrdersDocumentSubtypeCode"`
	NoteOrdersSubjectText                                    *string  `json:"NoteOrdersSubjectText"`
	NoteOrdersContentText                                    *string  `json:"NoteOrdersContentText"`
	NoteOrdersIdentifier                                     *string  `json:"NoteOrdersIdentifier"`
	SpecifiedBinaryFileIdentifier                            *string  `json:"SpecifiedBinaryFileIdentifier"`
	SpecifiedBinaryFileVersionIdentifier                     *string  `json:"SpecifiedBinaryFileVersionIdentifier"`
	SpecifiedBinaryFileNameText                              *string  `json:"SpecifiedBinaryFileNameText"`
	SpecifiedBineryFileURIIdentifier                         *string  `json:"SpecifiedBineryFileURIIdentifier"`
	SpecifiedBineryFileMIMECode                              *string  `json:"SpecifiedBineryFileMIMECode"`
	SpecifiedBineryFileEncodingCode                          *string  `json:"SpecifiedBineryFileEncodingCode"`
	SpecifiedBineryFileCode                                  *string  `json:"SpecifiedBineryFileCode"`
	SpecifiedBinaryFileDescriptionText                       *string  `json:"SpecifiedBinaryFileDescriptionText"`
	TradeSellerIdentifier                                    *string  `json:"TradeSellerIdentifier"`
	TradeSellerGlobalIdentifier                              *string  `json:"TradeSellerGlobalIdentifier"`
	TradeSellerName                                          *string  `json:"TradeSellerName"`
	TradeBillFromPartyRegisteredIdentifier                   *string  `json:"TradeBillFromPartyRegisteredIdentifier"`
	TradeContactSellerIdentifier                             *string  `json:"TradeContactSellerIdentifier"`
	TradeContactSellerPersonName                             *string  `json:"TradeContactSellerPersonName"`
	TradeContactSellerDepartmentName                         *string  `json:"TradeContactSellerDepartmentName"`
	SellerTelephoneNumber                                    *string  `json:"SellerTelephoneNumber"`
	SellerFaxNumber                                          *string  `json:"SellerFaxNumber"`
	SellerEmailAddress                                       *string  `json:"SellerEmailAddress"`
	SellerAddressPostalCode                                  *string  `json:"SellerAddressPostalCode"`
	SellerAddress                                            *string  `json:"SellerAddress"`
	TradeBuyerIdentifier                                     *string  `json:"TradeBuyerIdentifier"`
	TradeBuyerGlobalIdentifier                               *string  `json:"TradeBuyerGlobalIdentifier"`
	TradeBuyerName                                           *string  `json:"TradeBuyerName"`
	TradeContactBuyerIdentifier                              *string  `json:"TradeContactBuyerIdentifier"`
	TradeContactBuyerPersonName                              *string  `json:"TradeContactBuyerPersonName"`
	TradeContactBuyerDepartmentName                          *string  `json:"TradeContactBuyerDepartmentName"`
	BuyerTelephoneNumber                                     *string  `json:"BuyerTelephoneNumber"`
	BuyerFaxNumber                                           *string  `json:"BuyerFaxNumber"`
	BuyerEmailAddress                                        *string  `json:"BuyerEmailAddress"`
	BuyerAddressPostalCode                                   *string  `json:"BuyerAddressPostalCode"`
	BuyerAddress                                             *string  `json:"BuyerAddress"`
	ReferencedQuotationReplyDocumentIssureAssignedIdentifier *string  `json:"ReferencedQuotationReplyDocumentIssureAssignedIdentifier"`
	ReferencedQuotationReplyDocumentIssueDate                *string  `json:"ReferencedQuotationReplyDocumentIssueDate"`
	ReferencedQuotationReplyDocumentRevisionIdentifier       *string  `json:"ReferencedQuotationReplyDocumentRevisionIdentifier"`
	ReferencedQuotationReplyDocumentInformationText          *string  `json:"ReferencedQuotationReplyDocumentInformationText"`
	ReferencedQuotationReplyDocumentPurposeCode              *string  `json:"ReferencedQuotationReplyDocumentPurposeCode"`
	ReferencedQuotationReplyDocumentSubtypeCode              *string  `json:"ReferencedQuotationReplyDocumentSubtypeCode"`
	ReferencedSalesOrderDocumentIssureAddignedIdentifier     *string  `json:"ReferencedSalesOrderDocumentIssureAddignedIdentifier"`
	ReferencedSalesOrderDocumentIssueDate                    *string  `json:"ReferencedSalesOrderDocumentIssueDate"`
	ReferencedSalesOrderDocumentRevisionIdentifier           *string  `json:"ReferencedSalesOrderDocumentRevisionIdentifier"`
	ReferencedSalesOrderDocumentInformationText              *string  `json:"ReferencedSalesOrderDocumentInformationText"`
	ReferencedSalesOrderDocumentPurposeCode                  *string  `json:"ReferencedSalesOrderDocumentPurposeCode"`
	ReferencedSalesOrderDocumentSubtypeCode                  *string  `json:"ReferencedSalesOrderDocumentSubtypeCode"`
	RelevantTradePartyIdentifier                             *string  `json:"RelevantTradePartyIdentifier"`
	RelevantTradePartyGlobalIdentifier                       *string  `json:"RelevantTradePartyGlobalIdentifier"`
	RelevantTradePartyName                                   *string  `json:"RelevantTradePartyName"`
	RelevantTradePartyRoleCode                               *string  `json:"RelevantTradePartyRoleCode"`
	RelevantTradeContactCode                                 *string  `json:"RelevantTradeContactCode"`
	RelevantTradeContactPersonName                           *string  `json:"RelevantTradeContactPersonName"`
	ProjectIdentifier                                        *string  `json:"ProjectIdentifier"`
	ProjectName                                              *string  `json:"ProjectName"`
	InspectionEventTypeCode                                  *string  `json:"InspectionEventTypeCode"`
	InspectionEventDescriptionText                           *string  `json:"InspectionEventDescriptionText"`
	ProjectPeriodStartDate                                   *string  `json:"ProjectPeriodStartDate"`
	ProjectPeriodEndDate                                     *string  `json:"ProjectPeriodEndDate"`
	TradeShipToPartyIdentifier                               *string  `json:"TradeShipToPartyIdentifier"`
	TradeShipToPartyGlobalIdentifier                         *string  `json:"TradeShipToPartyGlobalIdentifier"`
	TradeShipToPartyName                                     *string  `json:"TradeShipToPartyName"`
	TradeShipToPartyContactIdentifier                        *string  `json:"TradeShipToPartyContactIdentifier"`
	TradeShipToPartyContactPersonName                        *string  `json:"TradeShipToPartyContactPersonName"`
	TradeShipToPartyContactDepartmentName                    *string  `json:"TradeShipToPartyContactDepartmentName"`
	TradeShipToPartyContactPersonIdentifier                  *string  `json:"TradeShipToPartyContactPersonIdentifier"`
	ShipToPartyTelephoneNumber                               *string  `json:"ShipToPartyTelephoneNumber"`
	ShipToPartyFaxNumber                                     *string  `json:"ShipToPartyFaxNumber"`
	ShipToPartyEmailAddress                                  *string  `json:"ShipToPartyEmailAddress"`
	ShipToPartyAddressPostalCode                             *string  `json:"ShipToPartyAddressPostalCode"`
	ShipToPartyAddress                                       *string  `json:"ShipToPartyAddress"`
	TradeShipFromPartyIdentifier                             *string  `json:"TradeShipFromPartyIdentifier"`
	TradeShipFromPartyName                                   *string  `json:"TradeShipFromPartyName"`
	SupplyChainOperationEventIdentifier                      *string  `json:"SupplyChainOperationEventIdentifier"`
	SupplyChainOperationEventOccurrenceDate                  *string  `json:"SupplyChainOperationEventOccurrenceDate"`
	SupplyChainEventDeliveryTypeCode                         *string  `json:"SupplyChainEventDeliveryTypeCode"`
	SupplyChainEventDeliveryDescription                      *string  `json:"SupplyChainEventDeliveryDescription"`
	InstructedTemperatureControlCode                         *string  `json:"InstructedTemperatureControlCode"`
	SupplyChainTradeCurrencyCode                             *string  `json:"SupplyChainTradeCurrencyCode"`
	TradeTaxCalculatedAmount                                 *float32 `json:"TradeTaxCalculatedAmount"`
	TradeTaxTypeCode                                         *string  `json:"TradeTaxTypeCode"`
	TradeTaxBasisAmount                                      *float32 `json:"TradeTaxBasisAmount"`
	TradeTaxCategoryCode                                     *string  `json:"TradeTaxCategoryCode"`
	TradeTaxCategoryName                                     *string  `json:"TradeTaxCategoryName"`
	TradeTaxRatePercent                                      *string  `json:"TradeTaxRatePercent"`
	TradeTaxGrandTotalAmount                                 *float32 `json:"TradeTaxGrandTotalAmount"`
	TradeTaxCalculationMethod                                *string  `json:"TradeTaxCalculationMethod"`
	TradePaymentTermsDescriptionText                         *string  `json:"TradePaymentTermsDescriptionText"`
	TradePaymentTermsTypeCode                                *string  `json:"TradePaymentTermsTypeCode"`
	TradeSettlementMonetarySummationTotalTaxAmount           *float32 `json:"TradeSettlementMonetarySummationTotalTaxAmount"`
	TradeOrdersSettlementMonetarySummationGrandTotalAmount   *float32 `json:"TradeOrdersSettlementMonetarySummationGrandTotalAmount"`
	TradeOrdersSettlementMonetarySummationNetTotalAmount     *float32 `json:"TradeOrdersSettlementMonetarySummationNetTotalAmount"`
	TradeOrdersMonetarySummationIncludingTaxesTotalAmount    *float32 `json:"TradeOrdersMonetarySummationIncludingTaxesTotalAmount"`
}
