package requests

type Item struct {
	ExchangedOrdersDocumentIdentifier                                      string   `json:"ExchangedOrdersDocumentIdentifier"`
	OrdersDocumentItemlineIdentifier                                       string   `json:"OrdersDocumentItemlineIdentifier"`
	OrdersDocumentItemlineStatusCode                                       *string  `json:"OrdersDocumentItemlineStatusCode"`
	OrdersDocumentItemlineStatusReasonCode                                 *string  `json:"OrdersDocumentItemlineStatusReasonCode"`
	OrdersDocumentItemIdentifier                                           *string  `json:"OrdersDocumentItemIdentifier"`
	OrdersDocumentItemBuyerAssignedCategoryCode                            *string  `json:"OrdersDocumentItemBuyerAssignedCategoryCode"`
	NoteOrdersItemItemSubjectText                                          *string  `json:"NoteOrdersItemItemSubjectText"`
	NoteOrdersItemContentText                                              *string  `json:"NoteOrdersItemContentText"`
	NoteOrdersItemIdentifier                                               *string  `json:"NoteOrdersItemIdentifier"`
	ReferencedQuotationReplyDocumentItemIssuerAssignedIdentifier           *string  `json:"ReferencedQuotationReplyDocumentItemIssuerAssignedIdentifier"`
	ReferencedQuotationReplyDocumentItemLineIdentifier                     *string  `json:"ReferencedQuotationReplyDocumentItemLineIdentifier"`
	ReferencedQuotationReplyDocumentItemRevisionIdentifier                 *string  `json:"ReferencedQuotationReplyDocumentItemRevisionIdentifier"`
	ReferencedQuotationReplyDocumentItemInformationText                    *string  `json:"ReferencedQuotationReplyDocumentItemInformationText"`
	ReferencedDocumentItemIssureAssignedIdentifier                         *string  `json:"ReferencedDocumentItemIssureAssignedIdentifier"`
	TradePriceTypeCode                                                     *string  `json:"TradePriceTypeCode"`
	TradeOrdersPriceChargeAmount                                           *float32 `json:"TradeOrdersPriceChargeAmount"`
	TradePriceBasisQuantity                                                *float32 `json:"TradePriceBasisQuantity"`
	TradePriceBasisUnitCode                                                *string  `json:"TradePriceBasisUnitCode"`
	TradeDeliveryTermsDescriptionText                                      *string  `json:"TradeDeliveryTermsDescriptionText"`
	SupplyChainTradeDeliveryRequestedQuantity                              *float32 `json:"SupplyChainTradeDeliveryRequestedQuantity"`
	SupplyChainTradeDeliveryPerPackageUnitQuantity                         *float32 `json:"SupplyChainTradeDeliveryPerPackageUnitQuantity"`
	SupplyChainTradeDeliveryPackageQuantity                                *float32 `json:"SupplyChainTradeDeliveryPackageQuantity"`
	SupplyChainTradeDeliveryProductUnitQuantity                            *float32 `json:"SupplyChainTradeDeliveryProductUnitQuantity"`
	QuantityUnitCode                                                       *string  `json:"QuantityUnitCode"`
	ItemTradeDeliverToPartyIdentifier                                      *string  `json:"ItemTradeDeliverToPartyIdentifier"`
	ItemTradeDeliverToPartyGlobalIdentifier                                *string  `json:"ItemTradeDeliverToPartyGlobalIdentifier"`
	ItemTradeDeliverToPartyName                                            *string  `json:"ItemTradeDeliverToPartyName"`
	ItemTradeDeliverToPartyContactPersonName                               *string  `json:"ItemTradeDeliverToPartyContactPersonName"`
	ItemTradeDeliverToPartyContactDepartment                               *string  `json:"ItemTradeDeliverToPartyContactDepartment"`
	ItemDeliverToPartyPhoneNumber                                          *string  `json:"ItemDeliverToPartyPhoneNumber"`
	ItemDeliverToPartyFaxNumber                                            *string  `json:"ItemDeliverToPartyFaxNumber"`
	ItemDeliverToPartyEMailAddress                                         *string  `json:"ItemDeliverToPartyEMailAddress"`
	ItemDeliverToPartyAddressPostalCode                                    *string  `json:"ItemDeliverToPartyAddressPostalCode"`
	ItemDeliverToPartyAddress                                              *string  `json:"ItemDeliverToPartyAddress"`
	DeliverInstructionsHandlingCode                                        *string  `json:"DeliverInstructionsHandlingCode"`
	SupplyChainEventRequirementOccurrenceDate                              *string  `json:"SupplyChainEventRequirementOccurrenceDate"`
	SupplyChainEventTypeCode                                               *string  `json:"SupplyChainEventTypeCode"`
	SupplyChainEventRequirementOccurrenceTime                              *string  `json:"SupplyChainEventRequirementOccurrenceTime"`
	LogisticsLocationIdentification                                        *string  `json:"LogisticsLocationIdentification"`
	LogisticsLocationName                                                  *string  `json:"LogisticsLocationName"`
	TradeTaxTypeCode                                                       *string  `json:"TradeTaxTypeCode"`
	ItemTradeTaxBasisAmount                                                *float32 `json:"ItemTradeTaxBasisAmount"`
	ItemTradeTaxCategoryCode                                               *string  `json:"ItemTradeTaxCategoryCode"`
	TradeTaxCategoryName                                                   *string  `json:"TradeTaxCategoryName"`
	ItemTradeTaxRateApplicablePercent                                      *float32 `json:"ItemTradeTaxRateApplicablePercent"`
	ItemTradeTaxGrandTotalAmount                                           *float32 `json:"ItemTradeTaxGrandTotalAmount"`
	ItemTradeOrdersSettlementMonetarySummationNetTotalAmount               *float32 `json:"ItemTradeOrdersSettlementMonetarySummationNetTotalAmount"`
	ItemTradeOrdersSettlementMonetarySummationIncludingTaxesNetTotalAmount *float32 `json:"ItemTradeOrdersSettlementMonetarySummationIncludingTaxesNetTotalAmount"`
	TradeProductIdentifier                                                 *string  `json:"TradeProductIdentifier"`
	TradeProductGlobalIdentifier                                           *string  `json:"TradeProductGlobalIdentifier"`
	TradeProductSellerAssignedIdentifier                                   *string  `json:"TradeProductSellerAssignedIdentifier"`
	TradeProductBuyerAssignedIdentifier                                    *string  `json:"TradeProductBuyerAssignedIdentifier"`
	TradeProductManufacturerAssignedIdentifier                             *string  `json:"TradeProductManufacturerAssignedIdentifier"`
	TradeProductName                                                       *string  `json:"TradeProductName"`
	TradeProductDescription                                                *string  `json:"TradeProductDescription"`
	TradeProductTypeCode                                                   *string  `json:"TradeProductTypeCode"`
	TradeProductEndItemTypeCode                                            *string  `json:"TradeProductEndItemTypeCode"`
	TradeProductSizeCode                                                   *string  `json:"TradeProductSizeCode"`
	TradeProductSizeDescriptionText                                        *string  `json:"TradeProductSizeDescriptionText"`
	ProductCharacteristicIdentifier                                        *string  `json:"ProductCharacteristicIdentifier"`
	ProductCharacteristicTypeCode                                          *string  `json:"ProductCharacteristicTypeCode"`
	ProductCharacteristicDescriptionText                                   *string  `json:"ProductCharacteristicDescriptionText"`
	ProductCharacteristicContentTypeCode                                   *string  `json:"ProductCharacteristicContentTypeCode"`
	TradeProductInstanceGlobalSerialIdentifier                             *string  `json:"TradeProductInstanceGlobalSerialIdentifier"`
	TradeProductInstanceBatchIdentifier                                    *string  `json:"TradeProductInstanceBatchIdentifier"`
	ReferenceQualityInspectionDocumentInformationText                      *string  `json:"ReferenceQualityInspectionDocumentInformationText"`
	TradeManufacturerIdentifier                                            *string  `json:"TradeManufacturerIdentifier"`
	TradeManufacturerName                                                  *string  `json:"TradeManufacturerName"`
	ReferencedTechnicalDocumentIssuerAssignedIdentifier                    *string  `json:"ReferencedTechnicalDocumentIssuerAssignedIdentifier"`
	ReferencedTechnicalDocumentRevisionIdentifier                          *string  `json:"ReferencedTechnicalDocumentRevisionIdentifier"`
	ReferencedTechnicalDocumentName                                        *string  `json:"ReferencedTechnicalDocumentName"`
	ReferencedTechnicalDocumentInformationText                             *string  `json:"ReferencedTechnicalDocumentInformationText"`
	ReferencedTechnicalDocumentAttachment                                  *string  `json:"ReferencedTechnicalDocumentAttachment"`
	ReferencedSupplyDocumentIssuerAssignedIdentifier                       *string  `json:"ReferencedSupplyDocumentIssuerAssignedIdentifier"`
	ReferencedSupplyDocumentAttachmentBinaryObject                         *string  `json:"ReferencedSupplyDocumentAttachmentBinaryObject"`
	ReferencedLogisticsPackageUnitQuantity                                 *float32 `json:"ReferencedLogisticsPackageUnitQuantity"`
	ReferencedLogisticsPackageQuantityUnitCode                             *string  `json:"ReferencedLogisticsPackageQuantityUnitCode"`
	ReferencedLogisticsPackageTypeCode                                     *string  `json:"ReferencedLogisticsPackageTypeCode"`
	GoodsProductionIdentifier                                              *string  `json:"GoodsProductionIdentifier"`
	GoodsProductionManufacturingProcessDescriptionText                     *string  `json:"GoodsProductionManufacturingProcessDescriptionText"`
}
